name: grid-correction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - PyQt6>=6.4.0
    - opencv-python>=4.7.0
    - numpy>=1.24.0
    - scikit-image>=0.19.0 